services:
  postgres:
    image: postgres:15-alpine
    container_name: telegram_app_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      NODE_ENV: ${NODE_ENV}
      BOT_USERNAME: ${BOT_USERNAME}
      ADMIN_TELEGRAM_ID: ${ADMIN_TELEGRAM_ID}
    restart: always

  # prisma-studio:
  #   build:
  #     context: .
  #     dockerfile: ./database/Dockerfile
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #   ports:
  #     - "5555:5555"
  #   restart: always

volumes:
  postgres_data:
