version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: telegram_app_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: ${NODE_ENV}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3000:3000"
    restart: always

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
      BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      NODE_ENV: ${NODE_ENV}
      BOT_USERNAME: ${BOT_USERNAME}
      ADMIN_TELEGRAM_ID: ${ADMIN_TELEGRAM_ID}
    restart: always

volumes:
  postgres_data:
