import type { Metadata } from "next";
import { Inter, Roboto, Roboto_Mono } from "next/font/google";
import "react-modern-drawer/dist/index.css";
import "./globals.css";
import TelegramLayout from "@/components/layout/telegram-layout";
import DeviceProvider from "@/components/providers/device-provider";
// import { TelegramAuthProvider } from "@/components/providers";
import { headers } from "next/headers";
import { QueryProvider } from "@/components/providers/query-provider";
import ToastProvider from "@/components/providers/toast-provider";
import TelegramProvider from "@/components/providers/telegram-provider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const userAgent = headersList.get("user-agent") || "";
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          async
          src="https://telegram.org/js/telegram-web-app.js"
        ></script>
        {/* <script
          async
          type="module"
          src="https://unpkg.com/@lottiefiles/lottie-player@2.0.12/dist/lottie-player.js"
        ></script> */}
        <script
          async
          type="module"
          src="https://unpkg.com/@lottiefiles/lottie-player@2.0.12/dist/tgs-player.js"
        ></script>
      </head>
      <body
        className={`${inter.variable} ${roboto.variable} ${robotoMono.variable} antialiased`}
      >
        <DeviceProvider userAgent={userAgent}>
          <ToastProvider>
            <QueryProvider>
              <TelegramProvider>
                {/* <TelegramAuthProvider> */}
                <TelegramLayout>{children}</TelegramLayout>
                {/* </TelegramAuthProvider> */}
              </TelegramProvider>
            </QueryProvider>
          </ToastProvider>
        </DeviceProvider>
      </body>
    </html>
  );
}
